# Generated by Django 4.2.23 on 2025-07-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0003_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(),
        ),
    ]
