# Generated by Django 4.2.23 on 2025-07-16 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0006_alter_city_latitude_alter_city_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="avg_time_minutes",
        ),
        migrations.AlterField(
            model_name="route",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes_destination",
                to="rides.city",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="distance_km",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="route",
            name="origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes_origin",
                to="rides.city",
            ),
        ),
    ]
