# Generated by Django 4.2.23 on 2025-07-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0007_remove_route_avg_time_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="avg_time_minutes",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Average time (minutes)"
            ),
        ),
    ]
